### ISSUE TITLE
CLRMD does not work with VS2015 / .NET 4.6

### ISSUE THREAD

**Issue by weltkante** [Microsoft/dotnetsamples#11]
After installing the VS2015 preview I can no longer attach to .NET 4.5 processes via Microsoft.Diagnostics.Runtime (neither the source version nor the nuget version work!)

Instead I get an exception "This runtime is not initialized and contains no data." when calling DataTarget.CreateRuntime

I assume this is because VS2015 updated the .NET runtime and CLRMD is no longer compatible, could someone update it maybe?

**Comment by lookuper** [comment]
Is there any updates on this, because I got this error both, when trying to attach or open dump?

**Comment by lookuper** [comment]
locate problem in RuntimeBase class:
    public RuntimeBase(DataTargetImpl dataTarget, DacLibrary lib)
    {
      this.m_dataTarget = dataTarget;
      this.m_library = lib;
      this.m_dacInterface = this.m_library.DacInterface;
      this.InitApi();
      this.m_dacInterface.Flush();
      IGCInfo gcInfo = this.GetGCInfo();
      if (gcInfo == null)
        throw new ClrDiagnosticsException("This runtime is not initialized and contains no data.", ClrDiagnosticsException.HR.RuntimeUninitialized);
      this.ServerGC = gcInfo.ServerMode;
      this.HeapCount = gcInfo.HeapCount;
      this.CanWalkHeap = gcInfo.GCStructuresValid && !dataTarget.DataReader.IsMinidump;
      this.m_dataReader = dataTarget.DataReader;
    }

Need some support from development team, or at least link to project if it has open sources.

**Comment by weltkante** [comment]
There is nothing you can do to fix this, the problem is that GetGCInfo is not implemented/available for the new .NET runtime installed by the CTP (it just returns null).

You may have some luck to look into dumps via VS2015 though.

**Comment by lookuper** [comment]
situation is not so bad as it seems, I've generate pdb file for this library and debug to DataTargetImplementation class, there I found CreateRuntime(String...) method thed returns ClrRuntime. Inside this method there is a check for major.minor.revision.patch properties of clr version. code something like:
        if (patch >= 1000)
          return (ClrRuntime) new V45Runtime(this, lib);
        else
           return (ClrRuntime) new LegacyRuntime(this, lib, version, patch);

In cases before 4.5.x patch version was more than '1000', in cases 4.5.x/4.6 runtimes patch is 0. So I decompiled library to IL code, path constant '1000' to became '0', save/compile/sign and map my project to patched version of the lib.
Checked with VS2015 CTP3-5, and frameworks/clr 4.0.30319/ 4.5.x/ 4.6/x all works as expected. I understand that this is not optimal solution, but work for me and I can continue work with lib on PC with latest updates. Possible errors in future due this hack, but I accept the risk. How development is going, as I saw last commit ~5 months ago, need to worry?
patched lib: 
https://github.com/lookuper/LiveProcessInspector/blob/master/LiveProcessInspector/LiveProcessInspector/Microsoft.Diagnostics.Runtime.dll

**Comment by weltkante** [comment]
Great work! I was assuming it wasn't working because the method was not implemented, but instead the runtime selection logic couldn't deal with the CTP reporting a zero patchlevel (but the version is correctly reported).

By the way, no need to disassemble the library, this project has the source for it - you can download and compile it yourself. I created PR #17 containing an improved version of your fix, I'm also checking for the specific version of the CTP to avoid issues with future versions. I don't care if the PR is merged but this should help out anyone needing a fix until the CTP is over.

PS: It is kinda sad that the fix was trivial and nobody from MS cared about it.

**Comment by mattwarren** [comment]
@weltkante thanks for doing a pull-request for the .NET 4.5.3/4.6 issue. I ran into the same problem and solved it in the same way, before noticing this discussion.

**Comment by weltkante** [comment]
Just for the record, the real problem is that the V4.0 runtime check only compares the major version and the patchlevel and totally ignores the minor version.

I updated the pull request to a more sensible check and only using the V4 DAC when minor < 6, but I can't test it to be 100% sure it works with previously released 4.0 and 4.5.* runtimes including service packs. It should be pretty safe though and I doubt any V4 runtime reports a version with minor >= 6

**Comment by weltkante** [comment]
I've cleaned up the PR history so it only contains the final change required to support .NET 4.6

**Comment by JeffCyr** [comment]
I tested your fix and it seem to work on a .Net 4.6 dump. The .Net 4.0, 4.5, 4.5.1 and 4.5.2 all have minor version = 0, so the check minor < 6 should be safe.

Reference:[Identifying the .NET version you are running](http://blogs.msdn.com/b/rodneyviana/archive/2014/12/23/identifying-the-net-version-you-are-running-2-0-4-5-4-5-1-or-4-5-2.aspx)

However, I don't know if there were breaking changes in the runtime between 4.5 and 4.6, so using the V45Runtime with .Net 4.6 might cause unexpected results, but it seem to work so far. It would be great to have some official feedback from Microsoft.

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
