### ISSUE TITLE
Minidumps: ClrRuntime.EnumerateModules() returns only mscorlib

### ISSUE THREAD

**Issue by claustopholt** [Microsoft/dotnetsamples#12]
I have some minidumps with limited data -- windbg says: "User Mini Dump File: Only registers, stack and portions of memory are available". Using SOS I can view file+line numbers in !ClrStack, example:

```
000000002029cab8 000000007766186a [HelperMethodFrame: 000000002029cab8] 
000000002029cba0 000007fe968163ff System.Reactive.Core.dll!Unknown
000000002029ee18 000007fef4f67b15 [HelperMethodFrame: 000000002029ee18] 
000000002029ef00 000007fe96c4fb96 System.Linq.Enumerable.SequenceEqual[[System.Double, mscorlib]](System.Collections.Generic.IEnumerable`1<Double>, System.Collections.Generic.IEnumerable`1<Double>, System.Collections.Generic.IEqualityComparer`1<Double>)
000000002029ef80 000007fe96c4ebcf Iit.TF.DataAccess.dll!Unknown [d:\Builds\88\4689\Sources\Source\DataAccess\Instruments\InstrumentComparer.cs @ 11]
000000002029f270 000007fe96c4e46a Iit.TF.DataAccess.dll!Unknown [d:\Builds\88\4689\Sources\Source\DataAccess\Instruments\InstrumentDataImporter.cs @ 70]
```

But using ClrMD, ClrRuntime.EnumerateModules() only returns mscorlib (so I can't load PDB files) and when walking the stack and outputting stackframe.DisplayString, I only get this:

```
System.Linq.Enumerable.SequenceEqual[[System.Double, mscorlib]](System.Collections.Generic.IEnumerable`1<Double>, System.Collections.Generic.IEnumerable`1<Double>, System.Collections.Generic.IEqualityComparer`1<Double>) 
Iit.TF.DataAccess.dll!Unknown 
Iit.TF.DataAccess.dll!Unknown 
```

If I attempt to use stackframe.GetFileAndLineNumber(), I get a ClrDiagnosticsException: "Failed to get PDB signature from module." which I assume makes sense because the modules are not there.

If I load larger dump files (same codebase) with full heap, the modules can be enumerated and the stack walk outputs the correct data.

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
