### ISSUE TITLE
IDebugControl interface with CLR.MD

### ISSUE THREAD

**Issue by fahadsuhaib** [Microsoft/dotnetsamples#13]
How do we use the IDebugControl interface to wait for events?

                IDebugControl control = (IDebugControl)dataTarget.DebuggerInterface;                
                var hr = control.SetExecutionStatus(DEBUG_STATUS.GO);
                var waitStatus = control.WaitForEvent(DEBUG_WAIT.DEFAULT, uint.MaxValue);

This doesn't seem to work, Any ideas or documentation would be really great!

**Comment by goldshtn** [comment]
@fahadsuhaib You might find [this blog post](http://blogs.microsoft.co.il/pavely/2015/07/27/writing-a-simple-debugger-with-dbgeng-dll/) useful.

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
