### ISSUE TITLE
Getting references to the objects in heap.

### ISSUE THREAD

**Issue by Anbu2388** [Microsoft/dotnetsamples#15]
The CLRMD works great. As it shows the class instances stored in heap and we can able to get the instance count as well as size of each instance occupied in heap.

It would be better if we can try to get, where these objects are referencing(stack trace of the object).

Or any better way to get the instance info, where it is created from.

Kindly help me on this @leculver ....

**Comment by dobrou** [comment]
A)
To get objects referenced FROM some object, try:
1) ClrType.Fields
example here:
https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiagExt/ClrObject.cs#L275

or 2)ClrType.EnumerateRefsOfObjectCarefully
details here:
http://www.nudoq.org/#!/Packages/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime/ClrType/M/EnumerateRefsOfObjectCarefully

B)
To get list of objects referencing TO some object:
You must compute this on your own using methods above.

This is short example how to create ILookup which list all references TO any object:

private static IEnumerable<ulong> EnumerateRefsOfObjectCarefully(ClrType type, ulong refFrom)
{
	var refsTo = new List<ulong>();
	type.EnumerateRefsOfObjectCarefully( refFrom, (refTo,i) => { refsTo.Add(refTo); });
	return refsTo;
}

public static ILookup<ulong, ulong> RefFromCache = null;
var references = 			
	from refFrom in heap.EnumerateObjects()
	let type = heap.GetObjectType(refFrom)
	let refsTo = EnumerateRefsOfObjectCarefully( type, refFrom)				
	from refTo in refsTo
	select new { refFrom, refTo }
;
RefFromCache = references.ToLookup( k => k.refTo , v => v.refFrom);

**Comment by Anbu2388** [comment]
@dobrou : Can we use this package from nuget with license?

I read that the code is redistributable. Whether it can be modified and uploaded in nuget?

What is procedure to use this dll from nuget with license?

Please assist me to achieve this.

Thanks in advance,
Anbu

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
