### ISSUE TITLE
ObjSize Not Working Correctly

### ISSUE THREAD

**Issue by Alois-xx** [Microsoft/dotnetsamples#16]
The sample https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/docs/WalkingTheHeap.md looks great. Unfortunately I do not get the numbers I am after. The problem is if that object has references back to some roots e.g. a static event handler which roots pretty much everything you get for all of your objects the same size which is not particularly helpful. 
Is there a simple way to solve this? 
E.g. EnumerateRefsOfObject could take a list of parent addresses which are known roots which should not be followed further to break this cyclic traversal.

**Comment by weltkante** [comment]
The diagnostics runtime only provides the tools to access the runtime, you still have to build the traversal and analysis functions yourself. If the sample doesn't give you the numbers you want you'll have to think about how to write the analysis you want ;-)

> E.g. EnumerateRefsOfObject could take a list of parent addresses which are known roots which should not be followed further to break this cyclic traversal.

So you just do this check yourself in the call site, in your traversal function. Pushing this check into EnumerateRefsOfObject makes no sense, if I understood it correctly it just enumerates the references of a single object and does not traverse paths. The traversal is the responsibility of the caller, and so is the check for cyclic paths.

**Comment by Alois-xx** [comment]
I have played a little bit further and you are right it is the responsibility of the caller. I was under the wrong impression that it traverses recursively the heap which is not true.

**Comment by goldshtn** [comment]
@Alois-xx If you're satisfied with the conclusion, perhaps consider closing this issue?

**Comment by Alois-xx** [comment]
Sure. Perfect Answer.
