### ISSUE TITLE
GetSourceLocationForOffset(..) not working

### ISSUE THREAD

**Issue by mattwarren** [Microsoft/dotnetsamples#18]
Unless I'm missing something [`GetSourceLocationForOffset(Address nativeOffset)`](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiag/Desktop/methods.cs#L90) doesn't work.

For starters it doesn't even use the `nativeOffset` parameters that is passed in, so I think that [this loop](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiag/Desktop/methods.cs#L121) should actually look like this:

``` csharp
    if (map[i].StartAddress <= nativeOffset && nativeOffset <= map[i].EndAddress)
    {
        ilOffset = map[i].ILOffset;
        break;
    }
```

But even given that change, I don't think it'll work. The problem is that it tries to locate the matching IL offset, given a native code offset. But in some code I'm working on, I see that the IL offsets are overlapping:

```
    ILOffset - [StartAddress-EndAddress]
    FFFFFFFE - [241390-24139A]
           0 - [24139A-24139A]
           0 - [24139A-2413A1]
           6 - [2413A1-2413A3]
           7 - [2413A3-2413A8]
           C - [2413A8-2413B9]
          12 - [2413B9-2413BB]
          13 - [2413BB-2413C0]
          18 - [2413C0-2413C0]
    FFFFFFFD - [2413C0-241390]
```

So if `24139A` was passed into [`GetSourceLocationForOffset(Address nativeOffset)`](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiag/Desktop/methods.cs#L90) it could come from within the range of either of the 2nd (`[24139A-24139A]`) or 3rd (`[24139A-2413A1]`) offset, what happens is that as soon as it finds a match it returns.

I've tried experimenting on getting the source offsets directly from the IL offset, without first going via a `nativeOffset`. It seems to be working, but it needed more changes to other code files, because it wasn't exposed, see https://github.com/mattwarren/dotnetsamples/commit/16519ff629291f8c390f277941c5b6ea773fe8d7

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
