### ISSUE TITLE
Memory readers are not thread-safe?

### ISSUE THREAD

**Issue by goldshtn** [Microsoft/dotnetsamples#21]
From some experimentation with parallelizing various heap traversal algorithms, I'm hitting odd exceptions that are only happening in multi-threaded usage of the same `ClrHeap`. To be clear, I am using only the ClrMD interface, not the DbgEng one.

Before I try to narrow down the repro, is the `ClrHeap` designed for multithreaded access? For example, enumerating segments in two different threads, or calling `NextObject` in two different threads? I'm seeing exceptions in low-level parts, such as the `DataReader`.

@leculver

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
