### ISSUE TITLE
Cannot load a dump file larger than 4GB

### ISSUE THREAD

**Issue by goldshtn** [Microsoft/dotnetsamples#24]
Attaching to a process with more than 4GB heap works great. Opening a dump file from that process fails with the following exception:

```
ClrDiagnosticsException: Failure loading DAC: CreateDacInstance failed 0x80131c4f
```

WinDbg + SOS are perfectly capable of loading the dump file. The problem seems to lie with the `ICLRDataTarget` implementation that CLRMD provides (in `DacDataTarget`); specifically, with the [`DumpReader`](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiag/Utilities/DumpReader.cs) class adapted from the MDBG sample. It says [in the comments](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/ClrMemDiag/Utilities/DumpReader.cs#L267) that the class was designed to handle 4GB dump files only.

**Comment by goldshtn** [comment]
Mdbg doesn't manage to read that kind of dump successfully, either. It doesn't crash but there are no active threads (`thread` returns nothing), no stack, etc. It seems to be using the same `DumpReader` class that's incorporated in CLRMD.

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
