### ISSUE TITLE
Dumps created by Procdump -r are not supported

### ISSUE THREAD

**Issue by goldshtn** [Microsoft/dotnetsamples#25]
**[Procdump](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) -r** creates a dump file without suspending the target process. Even for a very simple application, opening such a dump file with WinDbg + SOS works fine but fails with CLRMD. For example, `ClrThread.StackTrace` returns an empty collection of frames (whereas SOS produces a non-empty managed call stack).

**Comment by terrajobst** [comment]
We've moved CLR MD into its own [GitHub repository](http://github.com/microsoft/clrmd). If this issue still applies, please file it [there](http://github.com/microsoft/clrmd/issues/new).

Sorry for the inconvenience but we never intended for this repo to contain the component itself.
