### ISSUE TITLE
 Microsoft.Diagnostics.Runtime / CLRMD / Examples.sln references missing projects

### ISSUE THREAD

**Issue by codespare** [Microsoft/dotnetsamples#27]
```Microsoft.Diagnostics.Runtime/CLRMD/Examples.sln``` references

- ClrMemDiag\ClrMemDiag.csproj
- ClrMemDiagExt\ClrMemDiagExt.csproj

but those are not present in the git repository (yet? :)
It is a bit annoying mostly when building from the command line.

**Comment by weltkante** [comment]
If you dig the history they were previously part of the project and have been moved into their own repository, at https://github.com/Microsoft/clrmd

They weren't really examples but contained the CLRMD implementation and some utilities.

**Comment by codespare** [comment]
Is it possible to remove the entries from the .sln? They prevent building the solution with `msbuild.exe examples.sln` from the command line as it errors out.

**Comment by leculver** [comment]
Thank you for the report.  I have merged the pull request as well as updated all of the projects to use the most recent ClrMD NuGet package.

**Comment by codespare** [comment]
Works a charm, thank you!
